name: select_annotation
description: Annotations for the select code generator that are used in pair with it.
version: 0.1.0
maintainer: Yakov Karpov (@purplenoodlesoop)

homepage: https://github.com/purplenoodlesoop/select/tree/master/packages/select_annotation

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  meta: ^1.7.0

dev_dependencies:
  purple_lints: ^0.2.0
