publish_to: none

name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  freezed_annotation: ^2.0.3
  select_annotation: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  purple_lints: ^0.2.0
  select:
    path:
      ../
